import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Custom/Navbar";
import { ThemeProvider } from "@/Wrapper/theme-provider";
import Footer from "@/components/Custom/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anand Store",
  description: "Generated by Manash Anand",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
