import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Custom/Navbar";
import { ThemeProvider } from "@/Wrapper/theme-provider";
import Footer from "@/components/Custom/Footer";
import AuthProvider from "@/Wrapper/Authprovider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anand Store",
  description: "Generated by Manash Anand",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
